<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="LaBour" nsURI="http://www.example.org/LaBour" nsPrefix="LaBour">
  <eClassifiers xsi:type="ecore:EClass" name="BoulderingRoute">
    <eStructuralFeatures xsi:type="ecore:EReference" name="routestatement" upperBound="-1"
        eType="#//RouteStatement" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="Colour" instanceClassName="java.lang.Colour"/>
  <eClassifiers xsi:type="ecore:EClass" name="GridBasePoint" eSuperTypes="#//RouteStatement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="expr" lowerBound="2" upperBound="2"
        eType="#//Expr" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Hold" eSuperTypes="#//RouteStatement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="expr" lowerBound="5" upperBound="7"
        eType="#//Expr" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="Angle" instanceClassName="java.lang.Angle"/>
  <eClassifiers xsi:type="ecore:EClass" name="RouteStatement" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Grade" eSuperTypes="#//RouteStatement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="expr" lowerBound="1" eType="#//Expr"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Identifier" eSuperTypes="#//RouteStatement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="expr" lowerBound="1" eType="#//Expr"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Expr" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="x" eSuperTypes="#//integer"/>
  <eClassifiers xsi:type="ecore:EClass" name="y" eSuperTypes="#//integer"/>
  <eClassifiers xsi:type="ecore:EClass" name="string" abstract="true" eSuperTypes="#//Expr">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RouteGrade" eSuperTypes="#//string"/>
  <eClassifiers xsi:type="ecore:EClass" name="RouteID" eSuperTypes="#//string"/>
  <eClassifiers xsi:type="ecore:EClass" name="shape" eSuperTypes="#//string"/>
  <eClassifiers xsi:type="ecore:EClass" name="rotation" eSuperTypes="#//Expr">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="#//Angle"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="HoldColour" eSuperTypes="#//Expr">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="#//Colour"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="startinglabels" eSuperTypes="#//integer"/>
  <eClassifiers xsi:type="ecore:EClass" name="endlabel" eSuperTypes="#//Expr">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="integer" abstract="true" eSuperTypes="#//Expr">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="HoldRotation" eSuperTypes="#//Expr">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="#//Angle"/>
  </eClassifiers>
</ecore:EPackage>
